#!/usr/bin/python3
import random

def gcd(a, b):
    """Compute the greatest common divisor of a and b"""
    while b != 0:
        a, b = b, a % b
    return a

def pollard_rho(n):
    """Find a non-trivial factor of n using the Pollard-Rho algorithm"""
    x = random.randint(0, n - 1)
    y = x
    c = random.randint(0, n - 1)
    g = 1
    while g == 1:
        x = (x * x + c) % n
        y = (y * y + c) % n
        y = (y * y + c) % n
        g = gcd(abs(x - y), n)
    return g

def factorize(n):
    """Find the prime factors of n using the Pollard-Rho algorithm"""
    if n == 1:
        return []
    if n % 2 == 0:
        return [2] + factorize(n // 2)
    p = n
    while p == n:
        p = pollard_rho(n)
    return [p] + factorize(n // p)

def main():
    # Read the number to factorize from the input file
    with open(sys.argv[1], 'r') as f:
        n = int(f.read())

    # Factorize the number
    factors = factorize(n)
    print(factors)

if __name__ == "__main__":
    main()
